### ISSUE TITLE
current line is not highlighted

### ISSUE THREAD

**Issue by adrsta** [cpaulik/emacs-material-theme#39]
Hi cpaulik, really cool theme!
I'm enjoying it, especially the embossed headers in Org :]
The only problem I have is that:
hl-line-mode  has no effect for me neither in dark not light variant.

Do you know why?
It work for all other themes I have.

#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 3290c8a)
- Graphic display: t

**Comment by cpaulik** [comment]
What does `M-x describe-face highlight` give you?

It should be something like

```
Face: highlight (sample) (customize this face)

Documentation:
Basic face for highlighting.

Defined in `faces.el'.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: #37474f
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: nil
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified
```
for the dark theme.

Have you tried `global-hl-line-mode`?

**Comment by adrsta** [comment]
M-x describe-face highlight, gives me exactly the same output as for you
toggling global-hl-line-mode also no effect
other ideas? :]

**Comment by cpaulik** [comment]
Can you also look at the `hl-line` face? It should be 

```
Face: hl-line (sample) (customize this face)

Documentation:
Default face for highlighting the current line in Hl-Line mode.

Defined in `hl-line.el'.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: highlight
```

If that does not report anything strange then you might try  https://github.com/bruce/emacs-spacegray-theme ? It is the theme that material is based on and has the same elisp code, just different colors. 

If that does not give us any clues please update your packages and let me know where I can find your `.spacemacs`. Then we should have the same environment.
